### ISSUE TITLE
yarn test error missing polyfills.js

### ISSUE THREAD

**Issue by jbustamovej** [sw-yx/create-react-app-parcel#13]
When I run `yarn test` I get the following result:

yarn run v1.7.0
$ react-scripts-parcel test --env=jsdom
● Validation Error:

  Module /Users/joshua/Projects/elminda/create-react-app-parcel/node_modules/create-react-app-parcel-typescript/config/polyfills.js inthe setupFiles option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html

error Command failed with exit code 1.

**Comment by sw-yx** [comment]
hmm. polyfills.js was provided for C-R-A-P but not for CRAP-TS. oversight on my part, its a simple copy paste job and PR welcome. else will return to this in 1-2 weeks. appreciate the issue!
