### ISSUE TITLE
add typescript declaration file

### ISSUE THREAD

**Issue by jbustamovej** [sw-yx/create-react-app-parcel#14]
When I open src/App.tsx I immediately see an error "[ts] Cannot find module './logo.svg'.". The solution is to add a typescript declaration file with `declare module '*.svg'`

**Comment by sw-yx** [comment]
strange, I feel like I would have caught that. I assume you are using create-react-app-parcel-typescript? I'll happily take PRs if you wish, if not I'll attend to this in a week or two. thanks for the issue!
