### ISSUE TITLE
Content of 'public' folder doesn't get copied to /dist on 'yarn start'

### ISSUE THREAD

**Issue by mjsarfatti** [sw-yx/create-react-app-parcel#16]
As per the title, is this a wanted behaviour?
The function is called only in the build.js script.

**Comment by sw-yx** [comment]
hmm. CRAP should do whatever CRA does with regards to this. i didnt do any special modifications for file copying. does CRA copy public to /dist on yarn start?

**Comment by mjsarfatti** [comment]
Oh, I guess you are right. No, CRA copies the contents only on yarn build. I guess I can close this issue.

**Comment by sw-yx** [comment]
cheers tho
