### ISSUE TITLE
Choose a build location with react-scripts-parcel (outputs)

### ISSUE THREAD

**Issue by MichelDiz** [sw-yx/create-react-app-parcel#18]
Hi there!

How to do something like this?
` "build": "react-scripts-parcel build ./public/index.html -d build/ --public-url ./",`

I'm using (and work):
`"build": "parcel build ./public/index.html -d ./build --public-url ./",`
but I'm not sure if it's ok. Trying out Parcel with ElectronJS.

Cheers

**Comment by sw-yx** [comment]
hmm. you might be able to just add `"build:parcel": "parcel build ./public/index.html -d ./build --public-url ./",` to your npm scripts.

**Comment by MichelDiz** [comment]
Okay, as the option does not exist and using "parcel build" has no problems, so the issue is resolved.

Thank you!
