### ISSUE TITLE
Parcel by default doesn't watch&rebuild sass/scss, maybe CRAP should?

### ISSUE THREAD

**Issue by mjsarfatti** [sw-yx/create-react-app-parcel#19]
I don't know how to make CRAP watch sass unless I eject and configure Parcel.
Since it's something quite common could it be added to yarn start?

**Comment by sw-yx** [comment]
i think this is a good idea. its kinda my fault because i dont use sass/scss. would you like to do a PR?

**Comment by alexkrolick** [comment]
I thought it worked automatically when you install `node-sass`?

**Comment by mjsarfatti** [comment]
if that's the case there must be something wrong with my installation...
I'll investigate, and in case yes I'll do a PR 👍

**Comment by sw-yx** [comment]
thank you both for weighing in, i'm no expert in this stuff haha

**Comment by mjsarfatti** [comment]
So it turned out from time to time the LastPass extension will impede firefox from establishing WebSocket connections... 🤷‍♂️
I'm going to close this
