### ISSUE TITLE
Unminfied JS after building?

### ISSUE THREAD

**Issue by Daniel15** [sw-yx/create-react-app-parcel#21]
On a fresh CRAP app, I tried running `yarn build`. It worked, but the resulting file was not minified? Shouldn't it be minified?

Also, is there a way to split vendor code from app code by default? That's usually a best practice with building web apps.

**Comment by kevinvanryck** [comment]
Having the same issue with `npm run build ` not minifying/uglifying the code.

**Comment by sw-yx** [comment]
hey! sorry for late reply, ive been busy. i'm not sure why it doesnt do that - would happily take a PR if either of you can figure it out. its not a focus for me until Parcel v2 comes out and i have to migrate anyway :)

**Comment by sw-yx** [comment]
closing and seeking maintainer! https://github.com/sw-yx/create-react-app-parcel/issues/34
