### ISSUE TITLE
How can I remain all es6/es7 grammer?

### ISSUE THREAD

**Issue by jim-king-2000** [sw-yx/create-react-app-parcel#22]
I'm excited with create-react-app-parcel. However, I don't need the compatibility for IE and older browsers. My site needs only be opened in the latest Chrome/Edge/Firefox/Safari. So, I want almost all of the es6/es7 feature to be intact after build. Is it possible? If yes, how?

**Comment by sw-yx** [comment]
hi! hmm. i suggest you dont use CRAP then. just use straight parcel with no babel.

**Comment by jim-king-2000** [comment]
> hi! hmm. i suggest you dont use CRAP then. just use straight parcel with no babel.

I'm new to CRAP. How to use straight parcel with no babel in CRAP?

**Comment by sw-yx** [comment]
hmm. try deleting `.babelrc`? i havent tested it

**Comment by jim-king-2000** [comment]
It prints several lines of message and hangs.

`Built the bundle with browser support for >1%, last 4 versions, Firefox ESR, not ie < 11.`
