### ISSUE TITLE
upgrade to babel 7 - slow first start

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/create-react-app-parcel#26]
hi folks thank you for checking out my dinky little project.

i just did a bit of work upgrading to babel 7  but ran into fundamental issues with parcel 1 - see their repo over here: https://github.com/parcel-bundler/parcel/issues/868

i dont think i'll be able to fix this until the parcel 2 rewrite :(

anyway the new version of CRAP is 0.33, hopefully it works out for everyone - it runs in my tests but the first startup is now 48seconds long. subsequent startups are 3seconds.

**Comment by tomByrer** [comment]
The built-in demo for this repo seems to work:
https://github.com/godfreyzubiaga/parcel-react-boilerplate
Bare-bones + ESLint (Airbnb).  No ServiceWorker.

**Comment by sw-yx** [comment]
thanks tom! good info.

**Comment by sw-yx** [comment]
closing and seeking maintainer! https://github.com/sw-yx/create-react-app-parcel/issues/34
