### ISSUE TITLE
Rename manifest.json -> manifest.webmanifest

### ISSUE THREAD

**Issue by doppelganger9** [sw-yx/create-react-app-parcel#27]
## Steps to reproduce
- follow the README to install a new app,
- then run `yarn start`
- in the opened browser, inspect in Chrome Dev Tools > Application, and you might spot an error on the webmanifest.
<img width="428" alt="capture d ecran 2018-10-27 a 17 07 27" src="https://user-images.githubusercontent.com/316439/47605765-fe8d4780-da0a-11e8-896e-b6708b13ec50.png">

Parcel incorrectly transforms the manifest.json file:
<img width="644" alt="capture d ecran 2018-10-27 a 17 08 00" src="https://user-images.githubusercontent.com/316439/47605760-f7663980-da0a-11e8-96c4-2359351ae5b0.png">

## Explanation
Parcel only handle **webmanifests** when they have the `.webmanifest` extension.

Also, [.webmanifest is the standard extension in the specs](https://www.w3.org/TR/appmanifest/#media-type-registration).

## Proposed fix
IIRC, we should change this extension here:
https://github.com/sw-yx/create-react-app-parcel/blob/458b481ccb91c9c420f93d250f11f8896f43519e/packages/react-scripts-parcel/template/public/index.html#L12

And rename the `/packages/react-scripts-parcel/template/public/manifest.json` file to `/packages/react-scripts-parcel/template/public/manifest.webmanifest`.

Here what results in Chrome Dev Tools with the fix applied to a generated project:
<img width="425" alt="capture d ecran 2018-10-27 a 17 09 55" src="https://user-images.githubusercontent.com/316439/47605778-3a281180-da0b-11e8-95a9-b1431b68686f.png">

The manifest is correctly served:
<img width="660" alt="capture d ecran 2018-10-27 a 17 09 41" src="https://user-images.githubusercontent.com/316439/47605781-457b3d00-da0b-11e8-9d25-d2cad0b3af50.png">

**Comment by sw-yx** [comment]
thank you! not working on this now until parcel v2 comes out - will take note or accept a PR

**Comment by sw-yx** [comment]
closing and seeking maintainer! https://github.com/sw-yx/create-react-app-parcel/issues/34
