### ISSUE TITLE
Unsupported babel version: 7.0.0-beta.46

### ISSUE THREAD

**Issue by trxcllnt** [sw-yx/create-react-app-parcel#3]
[It seems like](https://github.com/parcel-bundler/parcel/issues/868) parcel doesn't support babel 7 yet. @tsiq-swyx what's your setup like?

**Comment by trxcllnt** [comment]
Ah nvm, locally installing `babel-core@6.26.3` into my project fixed it. btw ejecting doesn't seem to copy out `https://github.com/facebook/create-react-app/blob/next/packages/react-dev-utils/browsersHelper.js` into a local `./react-dev-utils` folder. seems like that's needed by the ejected `scripts/start.js`

**Comment by tsiq-swyx** [comment]
hmm sounds like i need to make it a devdependency? yeah the babel thing is
a bit confusing cos they have the @babel/core and the babel-core versions
and im not really sure which is which. ill have a look tmr. thanks!!

**Comment by tsiq-swyx** [comment]
downgraded the babel version to 6 and also addressed the ./react-dev-utils copy issue, thanks! i obviously havent tested the eject case enough :)
