### ISSUE TITLE
Error in building after install

### ISSUE THREAD

**Issue by saeedafroozi** [sw-yx/create-react-app-parcel#30]
Error in building after install!!!!!

Error:There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts-parcel package provided by Create React App requires a dependency:

  "eslint": "^4.19.1"

Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:

**Comment by sw-yx** [comment]
hmm. SKIP_PREFLIGHT_CHECK=true may help. looks like you have node modules somewhere up your tree. like the error says
