### ISSUE TITLE
Error when trying to start crap

### ISSUE THREAD

**Issue by YannisMarios** [sw-yx/create-react-app-parcel#31]
Hi I am getting the following error when trying to start crap on Windows 10

![Screenshot_2](https://user-images.githubusercontent.com/11289298/54344784-563eef00-464a-11e9-95f3-815903c4b957.png)

Then I also installed:

npm install --save eslint@4.19.1

after installing:
![Screenshot_4](https://user-images.githubusercontent.com/11289298/54346218-6b694d00-464d-11e9-83f0-a3550789dc2d.png)

No eslint is installed globally
![Screenshot_3](https://user-images.githubusercontent.com/11289298/54344879-88505100-464a-11e9-896b-565d6ea3a224.png)

my package.json:

```
{
  "name": "test3",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "eslint": "^4.19.1",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-scripts-parcel": "0.0.38"
  },
  "scripts": {
    "start": "react-scripts-parcel start",
    "build": "react-scripts-parcel build",
    "test": "react-scripts-parcel test --env=jsdom",
    "eject": "react-scripts-parcel eject"
  },
  "browserslist": {
    "development": [
      "last 2 chrome versions",
      "last 2 firefox versions",
      "last 2 edge versions"
    ],
    "production": [
      ">1%",
      "last 4 versions",
      "Firefox ESR",
      "not ie < 11"
    ]
  }
}
```
 Any help would be appreciated

**Comment by sw-yx** [comment]
hey thanks for trying it out! i definitely havent tested this on windows. please figure it out on your own for now as i am not working on this actively at the moment (will definitely get a bunch of activity when parcel 2 goes live)

**Comment by freitagdavid** [comment]
Just delete the ./node_modules/eslint folder I'm not sure what that is going to break but it at the very least got it starting for me. I'm on linux BTW and was running into the same issue.

**Comment by rheckart** [comment]
Same thing is happening on OSX.

**Comment by sw-yx** [comment]
PRs very welcome to fix it if anyone wants to pick this up!

**Comment by sw-yx** [comment]
closing and seeking maintainer! https://github.com/sw-yx/create-react-app-parcel/issues/34
