### ISSUE TITLE
I get a lot of warnings about outdated packages

### ISSUE THREAD

**Issue by talentlessguy** [sw-yx/create-react-app-parcel#32]
Please update some packages to remove these warnings.

```
warning react-scripts-parcel > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other too
ls.
warning react-scripts-parcel > fsevents@1.2.0: Way too old
warning react-scripts-parcel > babel-preset-react-app > babel-preset-env > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts-parcel > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
```

Browserslist, ESLint, babel-preset-react-app and fs-events should be updated

**Comment by sw-yx** [comment]
would you like to send in a PR? as it says on the README, this project isn't currently actively maintained right now while we wait for parcel 2. if you'd like to help with maintenance, we can discuss that too!

**Comment by talentlessguy** [comment]
@sw-yx, ok, I'll send a PR later

**Comment by sw-yx** [comment]
closing and seeking maintainer! https://github.com/sw-yx/create-react-app-parcel/issues/34
