### ISSUE TITLE
`cannot find autoprefixer` when building

### ISSUE THREAD

**Issue by talentlessguy** [sw-yx/create-react-app-parcel#33]
CRAP doesn't work when `yarn build`. Although simple Parcel + React setup (without CRAP) works nicely.

```
λ yarn build
yarn run v1.16.0
$ react-scripts-parcel build
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'autoprefixer'
Require stack:
- /mnt/c/Users/v1rtl/Desktop/Coding/test-stuff/compare-bundlers/parcel-app/node_modules/react-scripts-parcel/config/parcel.config.prod.js
- /mnt/c/Users/v1rtl/Desktop/Coding/test-stuff/compare-bundlers/parcel-app/node_modules/react-scripts-parcel/scripts/build.js
```

It seems that Autoprefixer is not included into CRAP, please fix.

**Comment by sw-yx** [comment]
would you like to send in a PR? as it says on the README, this project isn't currently actively maintained right now while we wait for parcel 2. if you'd like to help with maintenance, we can discuss that too!

**Comment by talentlessguy** [comment]
@sw-yx, ok, I'll send a PR

**Comment by sw-yx** [comment]
closing and seeking maintainer! https://github.com/sw-yx/create-react-app-parcel/issues/34
