### ISSUE TITLE
Add service-worker.js file to write listeners like push/fetch etc

### ISSUE THREAD

**Issue by srsajjad** [sw-yx/create-react-app-parcel#5]
Where we can simply write event listeners like self.addEventListener('push',e=>{})

**Comment by sw-yx** [comment]
We do already provide a service worker in the src: https://github.com/sw-yx/create-react-app-parcel/blob/master/packages/react-scripts-parcel/template/src/serviceWorker.js

but most people dont need it so i have left it unregistered (same as CRA v2.0)
https://github.com/sw-yx/create-react-app-parcel/blob/master/packages/react-scripts-parcel/template/src/index.js

**Comment by srsajjad** [comment]
Setting up sw-precache config and using  importScripts are a bit confusing. If there was a file where we could just write the listeners and the code would be pushed in the generated service-worker.js file (inside build folder), that would be great.

**Comment by sw-yx** [comment]
sorry for the delayed response!

is this standard practice? i dont use SW's so i dont know about this. can you please provide an example of another project where you can " just write the listeners and the code would be pushed in the generated service-worker.js file " or some other resource on SW's so i can learn more about this?

**Comment by sw-yx** [comment]
closing as inactive, feel free to reopen if important!
