### ISSUE TITLE
custom script --scrpits-version issue

### ISSUE THREAD

**Issue by nelreina** [sw-yx/create-react-app-parcel#6]
I published my own script on npm but when I run 
`create-react-app-parcel my-app --scripts-version custum-script`

this will try to download the script from github iso npm,
so I get an error with result that project is not created.

I ran this command with create-react-app and this works fine . 

Any suggestions?

**Comment by sw-yx** [comment]
i'm not sure as i haven't tried doing this myself. what would you like to change about the current scripts?

**Comment by nelreina** [comment]
Hi @tsiq-swyx , did you put the custom script in NPM ? 

I guess it will work when you try it from github, my problem is with npm.
My custom script exists on npm (not on github).

**Comment by nelreina** [comment]
@sw-yx 

>what would you like to change about the current scripts?

I want to create my custom setup with redux and react-router etc...

**Comment by sw-yx** [comment]
hello, yes, I put my custom script in npm. http://npm.im/create-react-app-parcel-typescript feel free to check out my code https://github.com/sw-yx/create-react-app-parcel-typescript/tree/master/packages/react-scripts-parcel you may have done something wrong by mistake. you just need to edit the [template folder](https://github.com/sw-yx/create-react-app-parcel-typescript/tree/master/packages/react-scripts-parcel/template)

**Comment by nelreina** [comment]
just 2 b sure.. u used this command  `create-react-app-parcel my-app --scripts-version custum-script` to create ur project ?

**Comment by sw-yx** [comment]
hi, you are supposed to fork the project to create the custom script, similar to create-react-app.

**Comment by tsiq-swyx** [comment]
sure thing. thanks for checking it out!
