### ISSUE TITLE
Using with typescript

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/create-react-app-parcel#7]
it should be possible to use CRAP with typescript since parcel is zero config with typescript. The steps so far:

1. `crap newproject` and `yarn add @types/react @types/react-dom`
2. (will PR to fix) go into `node_modules/react-scripts-parcel/scripts/start` and comment out `paths.appIndexJs` so it isn't required
3. rename `src/index.js` and `src/App.js` to .tsx, and go into `public/index.html` and change `index.js` to `index.tsx` accordingly.
4.  (can PR some sort of tsconfig) `declare var require: any` at top of `App.tsx`
5. yarn start

That should work, however i run into this weird error:

```
react-dom.development.js:15156 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at react-dom.development.js:15156
    at App.tsx:7
    at Object.parcelRequire.14.react (App.tsx:7)
    at newRequire (src.1eb0206c.js:48)
    at localRequire (src.1eb0206c.js:54)
    at Object.parcelRequire.8.react (react-dom.development.js:15435)
    at newRequire (src.1eb0206c.js:48)
    at parcelRequire.34 (src.1eb0206c.js:75)
    at src.1eb0206c.js:101
```

so i am not sure how to proceed but i am documenting here for now.

**Comment by tsiq-swyx** [comment]
mohsen says:

"@swyx instead of declaring require as any install `@types/node` and add “node” to your tsconfig.json “types” array"

**Comment by tsiq-swyx** [comment]
i have just published https://github.com/sw-yx/create-react-app-parcel-typescript and it should work out of the box! whoo

```
crap my-ts-app --scripts-version=create-react-app-parcel-typescript
```
