### ISSUE TITLE
npm run build throws error "Missing class properties transform"

### ISSUE THREAD

**Issue by jeffbski** [sw-yx/create-react-app-parcel#8]
Without changing any of the initial generated code, running `npm run build` throws a "Missing class properties transform" error.

```
jeffbski-mbp-2017:~/working/cra-parcel-ex1 [master]$ npm run build

> cra-parcel-ex1@0.1.0 build /Users/jeff/working/cra-parcel-ex1
> react-scripts-parcel build

Creating an optimized production build...
🚨  /Users/jeff/working/cra-parcel-ex1/src/App.js:6:2: /Users/jeff/working/cra-parcel-ex1/src/App.js: Missing class properties transform.
  4 |
  5 | class App extends Component {
> 6 |   state = { toggle: true };
    |   ^
  7 |   toggleToggle = () => this.setState({ toggle: !this.state.toggle });
  8 |   render() {
  9 |     const { toggle } = this.state;
Compiled successfully.
```

**Comment by sw-yx** [comment]
hey Jeff! that's strange. I would double check if the babel-preset-react plugin is installed correctly. will come back to this when I have more time.

**Comment by alexkrolick** [comment]
I think it's this: https://github.com/parcel-bundler/parcel/issues/867

Had a similar problem recently

**Comment by sw-yx** [comment]
that is super annoying. but will wait for them to fix it. thanks for jumping in

**Comment by juanmaguitar** [comment]
Same problem with fix in another repo. It solves the problem although is not a "definitive" solution → https://github.com/FezVrasta/react-popper/issues/187

**Comment by sw-yx** [comment]
hi folks, thanks for this! I will merge

**Comment by tsiq-swyx** [comment]
I have tested using v0.0.24 and it runs fine from fresh install!

thanks for filing, discussing, and fixing the issue, i love you all. this is kinda cool :)
