### ISSUE TITLE
npm test throws error on fresh app

### ISSUE THREAD

**Issue by osdevisnot** [sw-yx/create-react-app-parcel#9]
![image](https://user-images.githubusercontent.com/802242/41453807-f8fe9e98-702b-11e8-9bb1-b17f04dd551b.png)

**Comment by sw-yx** [comment]
hmm, why did this happen?

**Comment by tsiq-swyx** [comment]
I have tested using v0.0.24 and it runs fine from fresh install!

note that the `test` script is not supported yet.
